# Uncomment the next line to define a global platform for your project
#platform :ios, '8.0'
inhibit_all_warnings!

 
 
target 'AliyunVideoClient_Entrance' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # UI层面的pods
    pod 'LBXScan/LBXNative','~> 2.3'
    pod 'LBXScan/UI','~> 2.3'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'SDWebImage', '~> 4.0.0'

    # 数据管理与请求
    pod 'AFNetworking', '~> 3.0'
    pod 'FMDB',:git => 'https://github.com/ccgus/fmdb.git',:tag => '2.7'
    pod 'JSONModel','~> 1.7.0'

    #友盟crash收集
    pod 'UMCCommon','2.0.0'
    pod 'UMCAnalytics','6.0.1'










    target 'AliyunVideoClient_EntranceTests' do
        inherit! :search_paths
        # Pods for testing
    end

    target 'AliyunVideoClient_EntranceUITests' do
        inherit! :search_paths
        # Pods for testing
    end

end
